require 'pry'
require 'nokogiri'
require 'open-uri'
require 'launchy'
require 'colorize'
require 'catpix'
require 'spinning_cursor'

require_relative './pitchfork_best_new_music/version'
require_relative './pitchfork_best_new_music/cli'
require_relative './pitchfork_best_new_music/scraper'
require_relative './pitchfork_best_new_music/review'
require_relative './pitchfork_best_new_music/album'
require_relative './pitchfork_best_new_music/track'
require_relative './pitchfork_best_new_music/reissue'
